// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXchgHwd6iBIiUkcZnXbdrk18engsRvcU',
    appId: '1:959942176979:web:dd6cb0b52f8a59b8a72426',
    messagingSenderId: '959942176979',
    projectId: 'pushnotification-43ae5',
    authDomain: 'pushnotification-43ae5.firebaseapp.com',
    storageBucket: 'pushnotification-43ae5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3shHo9Qu2_dARy35zxiZig4B7a60yvqI',
    appId: '1:959942176979:android:1b0505f34acb7e31a72426',
    messagingSenderId: '959942176979',
    projectId: 'pushnotification-43ae5',
    storageBucket: 'pushnotification-43ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8o2UEmnDgN-2znpYBHCwauMZlx6LxQrU',
    appId: '1:959942176979:ios:7e61a444d7ea7f64a72426',
    messagingSenderId: '959942176979',
    projectId: 'pushnotification-43ae5',
    storageBucket: 'pushnotification-43ae5.appspot.com',
    iosBundleId: 'ku.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8o2UEmnDgN-2znpYBHCwauMZlx6LxQrU',
    appId: '1:959942176979:ios:7e61a444d7ea7f64a72426',
    messagingSenderId: '959942176979',
    projectId: 'pushnotification-43ae5',
    storageBucket: 'pushnotification-43ae5.appspot.com',
    iosBundleId: 'ku.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXchgHwd6iBIiUkcZnXbdrk18engsRvcU',
    appId: '1:959942176979:web:666b3258672ccd69a72426',
    messagingSenderId: '959942176979',
    projectId: 'pushnotification-43ae5',
    authDomain: 'pushnotification-43ae5.firebaseapp.com',
    storageBucket: 'pushnotification-43ae5.appspot.com',
  );
}
